name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the Project
    - name: Build the Project
      run: npm run build

    # Step 5: Deploy to Netlify
    - name: Deploy to Netlify
      run: |
        npm install -g netlify-cli
        npx netlify deploy --dir=./dist --json > deployment_logs.json
        DEPLOYED_URL=$(cat deployment_logs.json | jq -r '.deploy_url')
        if [ -z "$DEPLOYED_URL" ]; then
          echo "Error: Failed to capture deployed URL."
          exit 1
        fi
        echo "Deployed URL: $DEPLOYED_URL"
        echo "DEPLOYED_URL=$DEPLOYED_URL" >> $GITHUB_ENV

    # Step 6: Send Deployed URL to Backend
    - name: Send Deployed URL to Backend
      run: |
        if [ -z "${{ env.DEPLOYED_URL }}" ]; then
          echo "Error: Deployed URL is not set."
          exit 1
        fi
        curl -X POST https://folio4ubackend-production.up.railway.app/capture-deployed-url \
          -H "Content-Type: application/json" \
          -d "{\"deployedUrl\": \"${{ env.DEPLOYED_URL }}\"}"
