name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the Project
    - name: Build the Project
      run: npm run build

    # Step 5: Install Required Tools
    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    # Step 6: Retrieve Domain Name from Backend
    - name: Get Domain Name
      id: get-domain
      run: |
        DOMAIN=$(curl -s https://folio4ubackend-production.up.railway.app/get-domain | jq -r ".domain")
        if [ -z "$DOMAIN" ]; then
          echo "Error: No domain provided. Store a domain name before deploying."
          exit 1
        fi
        echo "Domain: $DOMAIN"
        echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV

    # Step 7: Create a New Netlify Site
    - name: Create Netlify Site
      id: create-site
      run: |
        SITE_DATA=$(npx netlify sites:create --name "$DOMAIN" --json)
        echo "Site Data: $SITE_DATA"
        SITE_ID=$(echo "$SITE_DATA" | jq -r ".id")
        echo "Site ID: $SITE_ID"
        echo "SITE_ID=$SITE_ID" >> $GITHUB_ENV
      env:
        NETLIFY_AUTH_TOKEN: "nfp_Mq3Z9Kkht9jmNEEfCYmJGKogzsfhV3SZded7"

    # Step 8: Deploy to the Newly Created Site
    - name: Deploy to Netlify
      run: |
        npx netlify deploy --prod --dir=./dist --site ${{ env.SITE_ID }}
      env:
        NETLIFY_AUTH_TOKEN: "nfp_Mq3Z9Kkht9jmNEEfCYmJGKogzsfhV3SZded7"
