name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the Project
    - name: Build the Project
      run: npm run build

    # Step 5: Install Netlify CLI
    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Install jq
      run: sudo apt-get install jq -y

    # Step 6: Retrieve Domain from Backend
    - name: Get Domain
      id: get-domain
      run: |
        DOMAIN=$(curl -s https://folio4ubackend-production.up.railway.app/get-subdomain | jq -r ".subdomain")
        if [ -z "$DOMAIN" ]; then
          echo "Error: No domain provided. Store a domain name before deploying."
          exit 1
        fi
        echo "Domain: $DOMAIN"
        echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV

    # Step 7: Deploy to Netlify
    - name: Deploy to Netlify
      run: |
        echo "Deploying to domain: $DOMAIN"
        npx netlify sites:create --name "$DOMAIN" --json || true
        npx netlify deploy --dir=./dist --alias "$DOMAIN"
      env:
        NETLIFY_AUTH_TOKEN: "nfp_Mq3Z9Kkht9jmNEEfCYmJGKogzsfhV3SZded7"
